/**
 * 定义各种距离
 */
package cn.chaohi.recommend.common;

public enum SIMILARITY {
	PEARSON, EUCLIDEAN, COSINE, TANIMOTO, LOGLIKELIHOOD, SPEARMAN, CITYBLOCK, FARTHEST_NEIGHBOR_CLUSTER, NEAREST_NEIGHBOR_CLUSTER
}